[package]
name = "devd-rs"
version = "0.1.0"
authors = [ "Greg V <greg@unrelenting.technology>" ]
keywords = [ "System", "FreeBSD", "devd", "hotplug" ]
categories = [ "os::unix-apis" ]
description = "An interface to FreeBSD's devd"
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/myfreeweb/devd-rs"
repository = "https://github.com/myfreeweb/devd-rs"

[dependencies]
nom = "3.2"
libc = "0"
